### ISSUE TITLE
latency error when trex-txrx-profile.py profile disables latency

### ISSUE THREAD

**Issue by k-rister** [atheurer/trafficgen#112]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./binary-search.py", line 1394, in handle_trial_process_stderr
    stats[device_pair['rx']]['rx_latency_lost_packets_pct'] = 100.0 * stats[device_pair['rx']]['rx_latency_lost_packets'] / stats[device_pair['tx']]['tx_latency_packets']
ZeroDivisionError: float division by zero

**Comment by k-rister** [comment]
Corrected by #114
